Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Invoke-ArmPut { param([string]$ResourceId,[string]$ApiVersion,$Body) $payload=$Body|ConvertTo-Json -Depth 40 -Compress;$response=Invoke-AzRestMethod -Method PUT -Path "${ResourceId}?api-version=$ApiVersion" -Payload $payload -ErrorAction Stop; if($response.StatusCode -notin 200,201,202){throw "ARM PUT failed for '$ResourceId' with status $($response.StatusCode): $($response.Content)"}; if($response.Content){$response.Content|ConvertFrom-Json -Depth 40}else{$null} }
function Get-WebRuntimeProperties { param([string]$Runtime,[bool]$Linux) if($Linux){return [ordered]@{linuxFxVersion=$Runtime}};switch -Regex($Runtime){'^DOTNET\|(.+)$'{return [ordered]@{netFrameworkVersion="v$($Matches[1].TrimStart('v'))"}}'^NODE\|(.+)$'{return [ordered]@{nodeVersion=$Matches[1]}}'^PHP\|(.+)$'{return [ordered]@{phpVersion=$Matches[1]}}default{throw "Unsupported Windows WEB_RUNTIME '$Runtime'. Use DOTNET|<version>, NODE|<version>, or PHP|<version>."}} }
function Resolve-AppService {
 [CmdletBinding(SupportsShouldProcess)]param($Configuration,$ManagedIdentity,$Monitoring,[switch]$ReuseOnly)
 Import-Module Az.Websites -ErrorAction Stop
 $planCfg=$Configuration.resources.appServicePlan;Write-DeploymentStatus -Stage AppService -Status Read -Message "Retrieving App Service plan $($planCfg.name)...";$plan=Get-AzAppServicePlan -ResourceGroupName $Configuration.resourceGroup.name -Name $planCfg.name -ErrorAction SilentlyContinue
 $linux=$Configuration.application.web.operatingSystem -eq 'Linux';$planId="/subscriptions/$($Configuration.subscriptionId)/resourceGroups/$($Configuration.resourceGroup.name)/providers/Microsoft.Web/serverfarms/$($planCfg.name)"
 if(-not $plan){if($planCfg.mode -eq 'Existing' -or $ReuseOnly){throw "App Service Plan '$($planCfg.name)' does not exist."};if($PSCmdlet.ShouldProcess($planCfg.name,'Create App Service Plan')){Write-DeploymentStatus -Stage AppService -Status Create -Message ("{0}: {1}..." -f 'Create App Service Plan',$planCfg.name);$tier=switch -Regex($Configuration.appService.sku){'^F'{ 'Free' }'^D'{ 'Shared' }'^B'{ 'Basic' }'^S'{ 'Standard' }'^P'{ 'PremiumV3' }default{'Basic'}};$body=[ordered]@{location=$Configuration.location;tags=$Configuration.tags;sku=[ordered]@{name=$Configuration.appService.sku;tier=$tier;capacity=$Configuration.appService.workerCount};kind=if($linux){'linux'}else{'app'};properties=[ordered]@{reserved=$linux}};$null=Invoke-ArmPut $planId '2024-11-01' $body;$plan=Get-AzAppServicePlan -ResourceGroupName $Configuration.resourceGroup.name -Name $planCfg.name -ErrorAction Stop}}
 else{Write-DeploymentStatus -Stage AppService -Status Read -Message "Validating existing App Service plan $($planCfg.name)...";if((-not (Test-AzureLocationMatch -Actual $plan.Location -Expected $Configuration.location))){throw "App Service Plan is in '$($plan.Location)', expected '$($Configuration.location)'."};if([bool]$plan.Reserved -ne $linux){throw "App Service Plan '$($planCfg.name)' operating system is incompatible with WEB_OS '$($Configuration.application.web.operatingSystem)'."}}
 $webCfg=$Configuration.resources.webApp;Write-DeploymentStatus -Stage AppService -Status Read -Message "Retrieving web app $($webCfg.name)...";$web=Get-AzWebApp -ResourceGroupName $Configuration.resourceGroup.name -Name $webCfg.name -ErrorAction SilentlyContinue;$webId="/subscriptions/$($Configuration.subscriptionId)/resourceGroups/$($Configuration.resourceGroup.name)/providers/Microsoft.Web/sites/$($webCfg.name)"
 if(-not $web){if($webCfg.mode -eq 'Existing' -or $ReuseOnly){throw "Web app '$($webCfg.name)' does not exist."};if($PSCmdlet.ShouldProcess($webCfg.name,'Create App Service web app')){Write-DeploymentStatus -Stage AppService -Status Create -Message ("{0}: {1}..." -f 'Create App Service web app',$webCfg.name);$identity=[ordered]@{type='UserAssigned';userAssignedIdentities=[ordered]@{$ManagedIdentity.id=[ordered]@{}}};$settings=@();foreach($key in $Configuration.application.web.appSettings.Keys){$settings+=@{name=$key;value=[string]$Configuration.application.web.appSettings[$key]}};if($Monitoring.applicationInsights.connectionString){$settings+=@{name='APPLICATIONINSIGHTS_CONNECTION_STRING';value=$Monitoring.applicationInsights.connectionString};$settings+=@{name='APPLICATIONINSIGHTS_AUTHENTICATION_STRING';value="Authorization=AAD;ClientId=$($ManagedIdentity.clientId)"}};$siteConfig=[ordered]@{alwaysOn=($Configuration.appService.sku -notmatch '^[FD]');healthCheckPath=$Configuration.application.web.healthPath;appSettings=$settings};foreach($entry in (Get-WebRuntimeProperties $Configuration.application.web.runtime $linux).GetEnumerator()){$siteConfig[$entry.Key]=$entry.Value};$body=[ordered]@{location=$Configuration.location;tags=$Configuration.tags;kind=if($linux){'app,linux'}else{'app'};identity=$identity;properties=[ordered]@{serverFarmId=$planId;httpsOnly=$true;keyVaultReferenceIdentity=$ManagedIdentity.id;siteConfig=$siteConfig}};$null=Invoke-ArmPut $webId '2024-11-01' $body;$web=Get-AzWebApp -ResourceGroupName $Configuration.resourceGroup.name -Name $webCfg.name -ErrorAction Stop}}
 else{Write-DeploymentStatus -Stage AppService -Status Read -Message "Validating existing web app $($webCfg.name)...";if((-not (Test-AzureLocationMatch -Actual $web.Location -Expected $Configuration.location))){throw "Web app is in '$($web.Location)', expected '$($Configuration.location)'."};if($web.ServerFarmId -and $web.ServerFarmId -ne $planId){throw "Web app '$($webCfg.name)' is attached to a different App Service Plan."}}
 [pscustomobject]@{plan=[pscustomobject]@{id=$planId;name=$planCfg.name;resource=$plan};webApp=[pscustomobject]@{id=$webId;name=$webCfg.name;resource=$web;hostName=if($web){$web.DefaultHostName}else{"$($webCfg.name).azurewebsites.net"};managedIdentityResourceId=$ManagedIdentity.id};preview=(-not $plan -or -not $web)}
}
Export-ModuleMember -Function Resolve-AppService
