Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Resolve-WorkerVm {
 [CmdletBinding(SupportsShouldProcess)]param($Configuration,$Network,$ManagedIdentity,[pscredential]$VmAdministratorCredential,[switch]$ReuseOnly)
 Import-Module Az.Compute -ErrorAction Stop;Import-Module Az.Network -ErrorAction Stop;$cfg=$Configuration.resources.workerVm;$vm=Get-AzVM -ResourceGroupName $Configuration.resourceGroup.name -Name $cfg.name -ErrorAction SilentlyContinue
 if($vm){if($vm.Location -ne $Configuration.location){throw "Worker VM is in '$($vm.Location)', expected '$($Configuration.location)'."};if($vm.StorageProfile.OsDisk.OsType -and [string]$vm.StorageProfile.OsDisk.OsType -ne $Configuration.application.worker.operatingSystem){throw "Worker VM operating system does not match WORKER_OS '$($Configuration.application.worker.operatingSystem)'."};return [pscustomobject]@{action='Reuse';resource=$vm;id=$vm.Id;name=$vm.Name;location=$vm.Location;operatingSystem=$Configuration.application.worker.operatingSystem;computerName=$Configuration.application.worker.computerName;managedIdentityResourceId=$ManagedIdentity.id;networkInterfaceId=$vm.NetworkProfile.NetworkInterfaces[0].Id;osDiskName=$vm.StorageProfile.OsDisk.Name}}
 if($cfg.mode -eq 'Existing' -or $ReuseOnly){throw "Worker VM '$($cfg.name)' does not exist."};$worker=$Configuration.application.worker;$nicName="$($Configuration.naming.resourceNamePrefix)-NIC-01";$nic=Get-AzNetworkInterface -ResourceGroupName $Configuration.resourceGroup.name -Name $nicName -ErrorAction SilentlyContinue
 if(-not $nic -and $PSCmdlet.ShouldProcess($nicName,'Create worker VM network interface')){$nic=New-AzNetworkInterface -ResourceGroupName $Configuration.resourceGroup.name -Name $nicName -Location $Configuration.location -SubnetId $Network.workerSubnetId -Tag $Configuration.tags -ErrorAction Stop}
 $nicId=if($nic){$nic.Id}else{"/subscriptions/$($Configuration.subscriptionId)/resourceGroups/$($Configuration.resourceGroup.name)/providers/Microsoft.Network/networkInterfaces/$nicName"}
 if(-not $PSCmdlet.ShouldProcess($cfg.name,'Create worker virtual machine')){return [pscustomobject]@{action='Create';id="/subscriptions/$($Configuration.subscriptionId)/resourceGroups/$($Configuration.resourceGroup.name)/providers/Microsoft.Compute/virtualMachines/$($cfg.name)";name=$cfg.name;location=$Configuration.location;operatingSystem=$worker.operatingSystem;computerName=$worker.computerName;managedIdentityResourceId=$ManagedIdentity.id;networkInterfaceId=$nicId;osDiskName="$($Configuration.naming.resourceNamePrefix)-OSDISK-01";preview=$true}}
 if(-not $nic){throw 'NIC creation did not return a resource.'};$vmConfig=New-AzVMConfig -VMName $cfg.name -VMSize $worker.vmSize;$vmConfig=Add-AzVMNetworkInterface -VM $vmConfig -Id $nic.Id;$vmConfig=Set-AzVMOSDisk -VM $vmConfig -Name "$($Configuration.naming.resourceNamePrefix)-OSDISK-01" -CreateOption FromImage -StorageAccountType StandardSSD_LRS
 $publisher=$worker.image.publisher;$offer=$worker.image.offer;$sku=$worker.image.sku;$version=$worker.image.version
 if($worker.operatingSystem -eq 'Linux'){
  if(-not(Test-StringPresent $publisher)){$publisher='Canonical'};if(-not(Test-StringPresent $offer)){$offer='0001-com-ubuntu-server-jammy'};if(-not(Test-StringPresent $sku)){$sku='22_04-lts-gen2'}
  $keyPath=(Resolve-Path -LiteralPath $worker.sshPublicKeyPath -ErrorAction Stop).Path;$key=(Get-Content -LiteralPath $keyPath -Raw).Trim();if($key -notmatch '^ssh-(rsa|ed25519|ecdsa) '){throw 'WORKER_SSH_PUBLIC_KEY_PATH does not contain a supported OpenSSH public key.'}
  $randomText=[Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(32));$random=[securestring]::new();foreach($character in $randomText.ToCharArray()){$random.AppendChar($character)};$random.MakeReadOnly();$cred=[pscredential]::new($worker.adminUsername,$random);$vmConfig=Set-AzVMOperatingSystem -VM $vmConfig -Linux -ComputerName $worker.computerName -Credential $cred -DisablePasswordAuthentication;$vmConfig=Add-AzVMSshPublicKey -VM $vmConfig -KeyData $key -Path "/home/$($worker.adminUsername)/.ssh/authorized_keys"
 } else {
  if($null -eq $VmAdministratorCredential){throw 'VmAdministratorCredential is required to create a Windows worker VM.'};if(-not(Test-StringPresent $publisher)){$publisher='MicrosoftWindowsServer'};if(-not(Test-StringPresent $offer)){$offer='WindowsServer'};if(-not(Test-StringPresent $sku)){$sku='2022-datacenter-azure-edition'};$vmConfig=Set-AzVMOperatingSystem -VM $vmConfig -Windows -ComputerName $worker.computerName -Credential $VmAdministratorCredential -ProvisionVMAgent -EnableAutoUpdate
 }
 $vmConfig=Set-AzVMSourceImage -VM $vmConfig -PublisherName $publisher -Offer $offer -Skus $sku -Version $version;$null=New-AzVM -ResourceGroupName $Configuration.resourceGroup.name -Location $Configuration.location -VM $vmConfig -Tag $Configuration.tags -ErrorAction Stop
 $vm=Get-AzVM -ResourceGroupName $Configuration.resourceGroup.name -Name $cfg.name -ErrorAction Stop;$null=Update-AzVM -ResourceGroupName $Configuration.resourceGroup.name -VM $vm -IdentityType UserAssigned -IdentityID $ManagedIdentity.id -ErrorAction Stop;$vm=Get-AzVM -ResourceGroupName $Configuration.resourceGroup.name -Name $cfg.name -ErrorAction Stop
 [pscustomobject]@{action='Create';resource=$vm;id=$vm.Id;name=$vm.Name;location=$vm.Location;operatingSystem=$worker.operatingSystem;computerName=$worker.computerName;managedIdentityResourceId=$ManagedIdentity.id;networkInterfaceId=$vm.NetworkProfile.NetworkInterfaces[0].Id;osDiskName=$vm.StorageProfile.OsDisk.Name}
}
Export-ModuleMember -Function Resolve-WorkerVm
