Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Invoke-BootstrapWorkflow {
 [CmdletBinding(SupportsShouldProcess)]param($Configuration,$RunContext,$Provenance)
 $providerResults=@();foreach($namespace in Get-RequiredProviderNamespaces){$provider=Get-AzResourceProvider -ProviderNamespace $namespace -ErrorAction Stop;$initialState=$provider.RegistrationState;if($initialState -ne 'Registered'){$action='Missing';if($Configuration.bootstrap.registerRequiredProviders){if($PSCmdlet.ShouldProcess($namespace,'Register Azure resource provider')){$null=Register-AzResourceProvider -ProviderNamespace $namespace -ErrorAction Stop;$provider=Get-AzResourceProvider -ProviderNamespace $namespace -ErrorAction Stop;$action='Registered'}else{$action='Register'}};$providerResults+=[pscustomobject]@{namespace=$namespace;initialState=$initialState;action=$action;finalState=$provider.RegistrationState};if(-not $WhatIfPreference -and $provider.RegistrationState -ne 'Registered'){throw "Provider '$namespace' registration is '$($provider.RegistrationState)'. Wait for registration to finish, then rerun Bootstrap."}}else{$providerResults+=[pscustomobject]@{namespace=$namespace;initialState='Registered';action='Reuse';finalState='Registered'}}}
 $group=Resolve-ResourceGroup -Configuration $Configuration -WhatIf:$WhatIfPreference;$identity=Resolve-ManagedIdentity -Configuration $Configuration -WhatIf:$WhatIfPreference
 [ordered]@{schemaVersion='1.0';artifactType='bootstrap';status=if($WhatIfPreference){'Preview'}else{'Ready'};runId=$RunContext.RunId;generatedAtUtc=(Get-Date).ToUniversalTime().ToString('o');environment=$Configuration.environment;tenantId=$Configuration.tenantId;subscriptionId=$Configuration.subscriptionId;location=$Configuration.location;resourceGroup=[ordered]@{name=$group.name;resourceId=$group.id;location=$group.location};managedIdentity=[ordered]@{name=$identity.name;resourceId=$identity.id;clientId=$identity.clientId;principalId=$identity.principalId;location=$identity.location};providers=$providerResults;provenance=$Provenance}
}
Export-ModuleMember -Function Invoke-BootstrapWorkflow
