Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Invoke-BootstrapWorkflow {
 [CmdletBinding(SupportsShouldProcess)]param($Configuration,$RunContext,$Provenance)
 $context=Get-AzContext -ErrorAction Stop
 $providerResults=@();foreach($namespace in Get-RequiredProviderNamespaces){Write-DeploymentStatus -Stage Bootstrap -Status Read -Message "Checking provider $namespace...";$provider=Get-DeploymentResourceProvider -Namespace $namespace -Context $context;$initialState=$provider.RegistrationState;if($initialState -ne 'Registered'){$action='Missing';if($Configuration.bootstrap.registerRequiredProviders){if($PSCmdlet.ShouldProcess($namespace,'Register Azure resource provider')){Write-DeploymentStatus -Stage Bootstrap -Status Update -Message "Registering Azure resource provider $namespace...";$null=Register-AzResourceProvider -ProviderNamespace $namespace -DefaultProfile $context -ErrorAction Stop;$provider=Get-DeploymentResourceProvider -Namespace $namespace -Context $context;$action='Registered';Write-DeploymentStatus -Stage Bootstrap -Message "Provider $namespace current registration: $($provider.RegistrationState)."}else{$action='Register'}};$providerResults+=[pscustomobject]@{namespace=$namespace;initialState=$initialState;action=$action;finalState=$provider.RegistrationState};if(-not $WhatIfPreference -and $provider.RegistrationState -ne 'Registered'){throw "Provider '$namespace' registration is '$($provider.RegistrationState)'. Wait for registration to finish, then rerun Bootstrap."}}else{Write-DeploymentStatus -Stage Bootstrap -Status Reuse -Message "Provider $namespace is already registered.";$providerResults+=[pscustomobject]@{namespace=$namespace;initialState='Registered';action='Reuse';finalState='Registered'}}}
 Add-RunEvent $RunContext Info 'Resolving the bootstrap resource group...'
 $group=Resolve-ResourceGroup -Configuration $Configuration -WhatIf:$WhatIfPreference;Add-RunEvent $RunContext $(if($WhatIfPreference){'Plan'}else{'Success'}) 'Resource group resolution completed.'
 Add-RunEvent $RunContext Info 'Resolving the shared managed identity...'
 $identity=Resolve-ManagedIdentity -Configuration $Configuration -WhatIf:$WhatIfPreference
 Add-RunEvent $RunContext $(if($WhatIfPreference){'Plan'}else{'Success'}) 'Shared managed identity resolution completed.'
 [ordered]@{schemaVersion='1.0';artifactType='bootstrap';status=if($WhatIfPreference){'Preview'}else{'Ready'};runId=$RunContext.RunId;generatedAtUtc=(Get-Date).ToUniversalTime().ToString('o');environment=$Configuration.environment;tenantId=$Configuration.tenantId;subscriptionId=$Configuration.subscriptionId;location=$Configuration.location;resourceGroup=[ordered]@{name=$group.name;resourceId=$group.id;location=$group.location};managedIdentity=[ordered]@{name=$identity.name;resourceId=$identity.id;clientId=$identity.clientId;principalId=$identity.principalId;location=$identity.location};providers=$providerResults;provenance=$Provenance}
}
Export-ModuleMember -Function Invoke-BootstrapWorkflow
